### ISSUE TITLE
did this pool support DEGO?

### ISSUE THREAD

**Issue by hunterqian1988** [turtlecoin/funky-turtle-pool#3]
dear funky:
    I set up this pool to DEGO, I set config.json like this.but it did not work.
"cnAlgorithm": "cryptonight_turtle",
"cnVariant": 2,
"cnBlobType": 2,

I need your help. thanks

**Comment by funkypenguin** [comment]
Did you set your daemontype to turtlecoin?

**Comment by hunterqian1988** [comment]
yes deamontype is turtlecoin like config_example turtle.json.

**Comment by hunterqian1988** [comment]
{
    "poolHost": "127.0.0.1",

    "coin": "hithelpinsurancetrust",
    "symbol": "HITC",
    "coinUnits": 75000000,
    "coinDecimalPlaces": 2,
    "coinDifficultyTarget": 30,

    "daemonType": "turtlecoin",
    "cnAlgorithm": "cryptonight-turtle",
    "cnVariant": 2,
    "cnBlobType": 2,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "hi2SapBm19B4f8Wszj2kuGBARpWz4hsLY2QX1WMNZASK7Rgz1CRCCPDEs4y1qrv7KHcSdY8uE7PkG2L4BXVuzDK71LX9PUuQA",
        "intAddressPrefix": 42,
        "subAddressPrefix": 42,
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "sslCert": "cert.pem",
        "sslKey": "privkey.pem",
        "sslCA": "fullchain.pem",
        "ports": [
            {
                "port": 1122,
                "difficulty": 2000,
                "desc": "Low end hardware"
            },
            {
                "port": 2233,
                "difficulty": 100000,
                "desc": "Mid range hardware"
            },
            {
                "port": 3344,
                "difficulty": 500000,
                "desc": "High end hardware"
            },
            {
                "port": 4455,
                "difficulty": 1000000,
                "desc": "Cloud-mining / NiceHash"
            },
            {
                "port": 6666,
                "difficulty": 3000,
                "desc": "Hidden port",
                "hidden": true
            },
            {
                "port": 6677,
                "difficulty": 1000000,
                "desc": "SSL connection",
                "ssl": false
            }
        ],
        "varDiff": {
            "minDiff": 100,
            "maxDiff": 1000000000,
            "targetTime": 60,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "paymentId": {
            "addressSeparator": "+"
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "blockTime": 60,
            "lastBlockCheckRate": 1
         }
    },

    "payments": {
        "enabled": true,
        "interval": 2160,
        "maxAddresses": 10,
        "mixin": 2,
        "priority": 0,
        "transferFee": 20000,
        "dynamicTransferFee": true,
        "minerPayFee" : true,
        "minPayment": 100000,
        "maxPayment": 25000000,
        "maxTransactionAmount": 50000000,
        "denomination": 100
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 30,
        "poolFee": 0.0,
        "devDonation": 0.0,
        "networkFee": 0.0
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "bindIp": "127.0.0.1",
        "port": 8117,
        "blocks": 60,
        "payments": 60,
        "password": "x",
        "ssl": false,
        "sslPort": 8119,
        "sslCert": "cert.pem",
        "sslKey": "privkey.pem",
        "sslCA": "fullchain.pem",
        "trustProxyIP": true
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 11211
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 11210
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null,
        "db": 0,
        "cleanupInterval": 15
    },

    "notifications": {
        "emailTemplate": "email_templates/default.txt",
        "emailSubject": {
            "emailAdded": "Your email was registered",
            "workerConnected": "Worker %WORKER_NAME% connected",
            "workerTimeout": "Worker %WORKER_NAME% stopped hashing",
            "workerBanned": "Worker %WORKER_NAME% banned",
            "blockFound": "Block %HEIGHT% found !",
            "blockUnlocked": "Block %HEIGHT% unlocked !",
            "blockOrphaned": "Block %HEIGHT% orphaned !",
            "payment": "We sent you a payment !"
        },
        "emailMessage": {
            "emailAdded": "Your email has been registered to receive pool notifications.",
            "workerConnected": "Your worker %WORKER_NAME% for address %MINER% is now connected from ip %IP%.",
            "workerTimeout": "Your worker %WORKER_NAME% for address %MINER% has stopped submitting hashes on %LAST_HASH%.",
            "workerBanned": "Your worker %WORKER_NAME% for address %MINER% has been banned.",
            "blockFound": "Block found at height %HEIGHT% by miner %MINER% on %TIME%. Waiting maturity.",
            "blockUnlocked": "Block mined at height %HEIGHT% with %REWARD% and %EFFORT% effort on %TIME%.",
            "blockOrphaned": "Block orphaned at height %HEIGHT% :(",
            "payment": "A payment of %AMOUNT% has been sent to %ADDRESS% wallet."
        },
        "telegramMessage": {
            "workerConnected": "Your worker _%WORKER_NAME%_ for address _%MINER%_ is now connected from ip _%IP%_.",
            "workerTimeout": "Your worker _%WORKER_NAME%_ for address _%MINER%_ has stopped submitting hashes on _%LAST_HASH%_.",
            "workerBanned": "Your worker _%WORKER_NAME%_ for address _%MINER%_ has been banned.",
            "blockFound": "*Block found at height* _%HEIGHT%_ *by miner* _%MINER%_*! Waiting maturity.*",
            "blockUnlocked": "*Block mined at height* _%HEIGHT%_ *with* _%REWARD%_ *and* _%EFFORT%_ *effort on* _%TIME%_*.*",
            "blockOrphaned": "*Block orphaned at height* _%HEIGHT%_ *:(*",
            "payment": "A payment of _%AMOUNT%_ has been sent."
        }
    },

    "email": {
        "enabled": false,
        "fromAddress": "your@email.com",
        "transport": "sendmail",
        "sendmail": {
            "path": "/usr/sbin/sendmail"
        },
        "smtp": {
            "host": "smtp.example.com",
            "port": 587,
            "secure": false,
            "auth": {
                "user": "username",
                "pass": "password"
            },
            "tls": {
                "rejectUnauthorized": false
            }
        },
        "mailgun": {
            "key": "your-private-key",
            "domain": "mg.yourdomain"
        }
    },

    "telegram": {
        "enabled": true,
        "botName": "POOL_BOT",
        "token": "POOL_BOT_TOKEN",
        "channel": "POOL_BOT_CHANNEL",
        "channelStats": {
            "enabled": false,
            "interval": 30
        },
        "botCommands": {
            "stats": "/stats",
            "report": "/report",
            "notify": "/notify",
            "blocks": "/blocks"
        }
    },
    
    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "prices": {
        "source": "cryptonator",
        "currency": "USD"
    },
    
    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "miners": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        },
        "blocks": {
            "enabled": true,
            "days": 30
        }
    }
}

**Comment by hunterqian1988** [comment]
if I run turtle.json then report errors
$ node init.js
Failed to read config file config.json

SyntaxError: Unexpected token { in JSON at position 1456
/home/hunter/pool/lib/logger.js:29
var logDir = config.logging.files.directory;
             ^

ReferenceError: config is not defined
    at Object.<anonymous> (/home/hunter/pool/lib/logger.js:29:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hunter/pool/init.js:17:1)
    at Module._compile (module.js:653:30)

**Comment by funkypenguin** [comment]
I merged a PR for a errant comma, check the latest commit and compare to your config?

--

**Comment by hunterqian1988** [comment]
thanks funky，I will try it

**Comment by hunterqian1988** [comment]
dear funky~~ when I mined at the pool。It show me wrong results。。。
I use SRBMINER and select turtle algo
message":"Rejected share: invalid result

**Comment by hunterqian1988** [comment]
hi funky:
I setup the pool now.but can not mining on it.. display cryptonight is not a function. 
friends tell me to use these 
git://github.com/turtlecoin/node8-multi-hashing
git://github.com/turtlecoin/node-cryptonote-util
did I need change that moudle?

**Comment by hunterqian1988** [comment]
http://39.106.143.90/  there is pool

**Comment by hunterqian1988** [comment]
it is working now
